language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs/dist
  on:
    branch: master
